# Generated by Django 5.0.7 on 2024-12-23 17:25

import django.db.models.deletion
import uuid
import xxxxxxxAPI.models.apiTokensModels
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APICall',
            fields=[
                ('id_api_call', models.AutoField(primary_key=True, serialize=False)),
                ('contact_id', models.CharField(blank=True, max_length=255)),
                ('id_salesforce', models.CharField(max_length=255)),
                ('datetime_alarm', models.CharField(max_length=255)),
                ('datetime_request', models.CharField(max_length=255)),
                ('displayed_number', models.CharField(max_length=20)),
                ('pin', models.CharField(blank=True, max_length=21, null=True)),
                ('company', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('location', models.TextField(blank=True)),
                ('site', models.TextField(blank=True)),
                ('phone', models.CharField(max_length=20)),
                ('endpoint', models.CharField(blank=True, max_length=255, null=True)),
                ('method', models.CharField(blank=True, max_length=10, null=True)),
                ('headers', models.JSONField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('payload_json', models.JSONField(blank=True, null=True)),
                ('response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'apicall',
            },
        ),
        migrations.CreateModel(
            name='APICallStatistics',
            fields=[
                ('id_api_call_stat', models.AutoField(primary_key=True, serialize=False)),
                ('endpoint', models.CharField(blank=True, max_length=191)),
                ('method', models.CharField(blank=True, max_length=10)),
                ('headers', models.JSONField(blank=True, null=True)),
                ('ip_hote', models.CharField(blank=True, max_length=50)),
                ('status', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'api_call_statistics',
            },
        ),
        migrations.CreateModel(
            name='APICallwxxxxxt',
            fields=[
                ('id_todo_from_wxxxxxt', models.AutoField(primary_key=True, serialize=False)),
                ('id_api_call', models.CharField(max_length=191)),
                ('contact_id', models.CharField(blank=True, max_length=255, null=True)),
                ('id_salesforce', models.CharField(max_length=255)),
                ('datetime_alarm', models.CharField(max_length=255)),
                ('datetime_request', models.CharField(max_length=255)),
                ('displayed_number', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('location', models.TextField(blank=True)),
                ('site', models.TextField(blank=True)),
                ('phone', models.CharField(max_length=20)),
                ('pin_uxxx_sender', models.TextField(blank=True)),
                ('endpoint', models.CharField(blank=True, max_length=255, null=True)),
                ('method', models.CharField(blank=True, max_length=10, null=True)),
                ('headers', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('payload_json', models.JSONField(blank=True, null=True)),
                ('api_response', models.TextField(blank=True, null=True)),
                ('created_at', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'todo_from_wxxxxxt',
            },
        ),
        migrations.CreateModel(
            name='APIRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_data', models.JSONField()),
                ('response_data', models.JSONField()),
                ('response_status', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'wxxxxxt_request_log',
            },
        ),
        migrations.CreateModel(
            name='APIStatsSelforce',
            fields=[
                ('id_stats_selforce', models.AutoField(primary_key=True, serialize=False)),
                ('id_cxxxxe_sender', models.CharField(blank=True, max_length=50)),
                ('salesforce_id', models.CharField(blank=True, max_length=50)),
                ('salesforce_datetime', models.CharField(blank=True, max_length=191)),
                ('final_cxxxxe_status', models.CharField(blank=True, max_length=50)),
                ('cxxxxe_status', models.JSONField(blank=True, default=dict, null=True)),
                ('cxxxxe_status_detail', models.JSONField(blank=True, default=dict, null=True)),
                ('nb_attempt', models.IntegerField(blank=True, null=True)),
                ('uxxx_id', models.TextField(blank=True)),
                ('uxxx_datetime', models.CharField(blank=True, max_length=191)),
                ('inocx_id', models.TextField(blank=True)),
                ('inocx_datetime', models.CharField(blank=True, max_length=191)),
                ('inocx_status', models.JSONField(blank=True, default=dict, null=True)),
                ('call_duration_details', models.JSONField(blank=True, default=dict, null=True)),
                ('call_duration', models.CharField(blank=True, max_length=191)),
                ('retour_uxxx', models.JSONField(blank=True, default=dict, null=True)),
                ('update_salesforce', models.JSONField(blank=True, default=dict, null=True)),
                ('raison_crash', models.TextField(blank=True)),
                ('create_at', models.CharField(blank=True, max_length=25)),
            ],
            options={
                'db_table': 'api_stats_selforce',
            },
        ),
        migrations.CreateModel(
            name='InoCxTask',
            fields=[
                ('id_inocx_task', models.AutoField(primary_key=True, serialize=False)),
                ('id_cible', models.CharField(max_length=191)),
                ('id_cxxxxe_sender', models.CharField(max_length=191)),
                ('attempt_number', models.IntegerField(blank=True, null=True)),
                ('contact_id', models.CharField(blank=True, max_length=255)),
                ('id_salesforce', models.CharField(max_length=255)),
                ('datetime_alarm', models.DateTimeField(blank=True, null=True)),
                ('datetime_request', models.DateTimeField(blank=True, null=True)),
                ('displayed_number', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('location', models.TextField(blank=True)),
                ('phone', models.CharField(max_length=20)),
                ('pin_uxxx_sender', models.CharField(max_length=191)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('payload_json', models.JSONField(blank=True, null=True)),
                ('start_point', models.CharField(max_length=255)),
                ('code_back_call', models.TextField(blank=True, null=True)),
                ('response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'inoCx_task_followup',
            },
        ),
        migrations.CreateModel(
            name='APIToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=wxxxxxtAPI.models.apiTokensModels.get_default_expiration)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'apitoken',
            },
        ),
        migrations.CreateModel(
            name='TransmittedAPICall',
            fields=[
                ('id_transmitted', models.AutoField(primary_key=True, serialize=False)),
                ('transmitted_to', models.CharField(max_length=191)),
                ('transmitted_status', models.IntegerField()),
                ('transmitted_response', models.JSONField(blank=True, null=True)),
                ('transmitted_at', models.DateTimeField(auto_now_add=True)),
                ('api_call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wxxxxxtAPI.apicall')),
            ],
            options={
                'db_table': 'transmitted_apicall',
            },
        ),
    ]
