# Generated by Django 4.2.1 on 2024-07-29 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wifirstAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apicall',
            name='body',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apicall',
            name='response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apicall',
            name='status',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='TransmittedAPICall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transmitted_to', models.CharField(max_length=255)),
                ('transmitted_status', models.IntegerField()),
                ('transmitted_response', models.JSONField(blank=True, null=True)),
                ('transmitted_at', models.DateTimeField(auto_now_add=True)),
                ('api_call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wifirstAPI.apicall')),
            ],
        ),
    ]
