# Generated by Django 5.0.7 on 2024-07-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifirstAPI', '0002_alter_apicall_body_alter_apicall_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicall',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apicall',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
