# Generated by Django 4.2.1 on 2024-07-29 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifirstAPI', '0003_apicall_error_message_alter_apicall_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apicall',
            name='status',
            field=models.IntegerField(),
        ),
    ]
