# Generated by Django 5.0.7 on 2024-07-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifirstAPI', '0004_alter_apicall_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apicall',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
