# Generated by Django 4.2.1 on 2024-07-30 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifirstAPI', '0005_alter_apicall_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='APICallStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('headers', models.JSONField()),
                ('status', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
