# Generated by Django 4.2.1 on 2024-08-02 13:06

import wifirstAPI.models.apiTokensModels
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wifirstAPI', '0007_apitoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicall',
            name='company',
            field=models.CharField(default='Default Company', max_length=255),
        ),
        migrations.AddField(
            model_name='apicall',
            name='contact',
            field=models.CharField(default='Default Contact', max_length=255),
        ),
        migrations.AddField(
            model_name='apicall',
            name='datetime_alarm',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='apicall',
            name='datetime_request',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='apicall',
            name='id_request',
            field=models.CharField(default='Default Request ID', max_length=255),
        ),
        migrations.AddField(
            model_name='apicall',
            name='id_salesforce',
            field=models.CharField(default='Default Salesforce ID', max_length=255),
        ),
        migrations.AddField(
            model_name='apicall',
            name='location',
            field=models.TextField(default='Default Location'),
        ),
        migrations.AddField(
            model_name='apicall',
            name='phone',
            field=models.CharField(default='0000000000', max_length=20),
        ),
        migrations.AlterField(
            model_name='apitoken',
            name='expires_at',
            field=models.DateTimeField(default=wifirstAPI.models.apiTokensModels.get_default_expiration),
        ),
    ]
