# Generated by Django 4.2.1 on 2024-08-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifirstAPI', '0008_apicall_company_apicall_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apicall',
            name='company',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='apicall',
            name='contact',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='apicall',
            name='datetime_alarm',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='apicall',
            name='datetime_request',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='apicall',
            name='id_request',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='apicall',
            name='id_salesforce',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='apicall',
            name='location',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='apicall',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
