# Generated by Django 4.2.1 on 2024-08-02 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wifirstAPI', '0009_alter_apicall_company_alter_apicall_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apicall',
            name='body',
        ),
    ]
