# Generated by Django 4.2.1 on 2024-08-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifirstAPI', '0010_remove_apicall_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apicall',
            name='datetime_alarm',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apicall',
            name='datetime_request',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
