# Generated by Django 4.2.1 on 2024-08-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifirstAPI', '0011_alter_apicall_datetime_alarm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apicall',
            name='datetime_alarm',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='apicall',
            name='datetime_request',
            field=models.CharField(max_length=255),
        ),
    ]
