# Generated by Django 4.2.1 on 2024-08-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifirstAPI', '0012_alter_apicall_datetime_alarm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apicall',
            name='headers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apicall',
            name='method',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='apicallstatistics',
            name='endpoint',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='apicallstatistics',
            name='headers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apicallstatistics',
            name='method',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
