# Generated by Django 4.2.1 on 2024-08-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifirstAPI', '0013_alter_apicall_headers_alter_apicall_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apicall',
            name='endpoint',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
