# Generated by Django 4.2.1 on 2024-08-05 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wifirstAPI', '0014_alter_apicall_endpoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apicall',
            name='id_request',
        ),
    ]
