# Generated by Django 5.0.7 on 2024-08-08 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifirstAPI', '0015_remove_apicall_id_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicall',
            name='contact_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apicall',
            name='displayed_number',
            field=models.CharField(default=111111, max_length=20),
            preserve_default=False,
        ),
    ]
